### ISSUE TITLE
Splunk Connector not working

### ISSUE THREAD

**Issue by questsin** [Apisero-Connectors/mule4-splunk-connector-doc#1]
on windies 10 Enterprise and Anypoint Studio 7.8.0 and Splunk 8.1.3 running locally.

When I test the splunk mule 4 configurations with the right base URL of "http://127.0.0.1:8000/" I get the bellow error while its worth noting that
Splunk Http Logger works.

java.lang.IllegalArgumentException: The 'errorTypeDefinition' argument can not be null
  java.lang.IllegalArgumentException: The 'errorTypeDefinition' argument can not be null
  	at org.mule.runtime.api.util.Preconditions.checkArgument(Preconditions.java:25)
  	at org.mule.runtime.extension.api.exception.ModuleException.<init>(ModuleException.java:68)
  	at org.mule.runtime.extension.api.exception.ModuleException.<init>(ModuleException.java:77)
  	at com.mulesoft.connectors.splunk.internal.error.exception.SplunkException.<init>(SplunkException.java:31)
  	at com.mulesoft.connectors.splunk.internal.error.exception.ExceptionHandler.checkErrorResponse(ExceptionHandler.java:41)
  	at com.mulesoft.connectors.splunk.internal.connection.SplunkConnection.validate(SplunkConnection.java:96)
  	at org.mule.connectors.commons.template.connection.ConnectorConnectionProvider.validate(ConnectorConnectionProvider.java:16)
  	at com.mulesoft.connectors.splunk.internal.connection.provider.SplunkConnectionProvider.validate(SplunkConnectionProvider.java:55)
  	at org.mule.runtime.module.extension.internal.runtime.config.ClassLoaderConnectionProviderWrapper.validate(ClassLoaderConnectionProviderWrapper.java:72)
  	at org.mule.runtime.core.internal.connection.ReconnectableConnectionProviderWrapper.validate(ReconnectableConnectionProviderWrapper.java:50)
  	at org.mule.runtime.core.internal.connection.ErrorTypeHandlerConnectionProviderWrapper.validate(ErrorTypeHandlerConnectionProviderWrapper.java:85)
  	at org.mule.runtime.core.internal.connection.DefaultConnectionManager.doTestConnectivity(DefaultConnectionManager.java:186)
  	at org.mule.runtime.core.internal.connection.DefaultConnectionManager.lambda$testConnectivity$1(DefaultConnectionManager.java:169)
  	at org.mule.runtime.core.internal.connection.DefaultConnectionManager.doTestConnectivity(DefaultConnectionManager.java:176)
  	at org.mule.runtime.core.internal.connection.DefaultConnectionManager.testConnectivity(DefaultConnectionManager.java:152)
  	at org.mule.runtime.core.internal.connection.DelegateConnectionManagerAdapter$EagerConnectionManagerAdapter.testConnectivity(DelegateConnectionManagerAdapter.java:176)
  	at org.mule.runtime.core.internal.connection.DelegateConnectionManagerAdapter.testConnectivity(DelegateConnectionManagerAdapter.java:98)
  	at org.mule.runtime.module.extension.api.tooling.ExtensionConnectivityTestingStrategy.testConnectivity(ExtensionConnectivityTestingStrategy.java:82)
  	at org.mule.runtime.core.internal.connectivity.DefaultConnectivityTestingService.testConnection(DefaultConnectivityTestingService.java:88)
  	at org.mule.runtime.config.internal.LazyConnectivityTestingService.testConnection(LazyConnectivityTestingService.java:57)
  	at com.mulesoft.agent.services.tooling.MuleAgentConnectivityTestingService.testConnection(MuleAgentConnectivityTestingService.java:77)
  	at com.mulesoft.agent.external.handlers.tooling.ToolingRequestHandler.lambda$applicationTestConnection$19(ToolingRequestHandler.java:482)
  	at com.mulesoft.agent.util.ResponseHelper.response(ResponseHelper.java:88)
  	at com.mulesoft.agent.external.handlers.tooling.ToolingRequestHandler.applicationTestConnection(ToolingRequestHandler.java:481)
  	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
  	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
  	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
  	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
  	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
  	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
  	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
  	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
  	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
  	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
  	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
  	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
  	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
  	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
  	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
  	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
  	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
  	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
  	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
  	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:876)
  	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
  	at com.mulesoft.agent.rest.RequestLoggingFilter.doFilter(RequestLoggingFilter.java:95)
  	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
  	at com.mulesoft.agent.rest.AuthorizationFilter.doFilter(AuthorizationFilter.java:49)
  	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
  	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
  	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
  	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
  	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
  	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
  	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
  	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
  	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
  	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
  	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
  	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
  	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
  	at org.eclipse.jetty.server.Server.handle(Server.java:505)
  	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
  	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
  	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
  	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
  	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
  	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
  	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
  	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
  	at java.lang.Thread.run(Thread.java:748)

**Comment by swichbalde** [comment]
Hello. i have same error could you please share with me solutions if you have :)

**Comment by sravannerella** [comment]
Hello @swichbalde and @questsin ,

After a lot of research, I figured out.

1. Splunk uses 8000 port for web UI meaning just the interface. Your actual splunk service runs on port 8089. 
2. Protocol should be `https` not `http`. Set your base url to `https://localhost:8089`. (refer to image 1)
3. Inside Splunk Global Configuration, Go into Security Section and set the protocol to HTTPS and in the TLS configuration check the Insecure option. (Refer to Image 2)  f.png"> 
<img width="620" alt="image" src="https://user-images.githubusercontent.com/12230220/169202695-150cb471-a59a-45a9-9cd8-4ac9bf8cec2f.png">

<img width="624" alt="image" src="https://user-images.githubusercontent.com/12230220/169202746-40326dcf-82a3-4b5c-8198-b92c1eaf072e.png">

Hope this helps! 👍

**Comment by swichbalde** [comment]
Tank you so much. That helped me ❤️
